name: kaylordut_interfaces CI

# 触发工作流的事件
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # 在 GitHub 提供的虚拟机上运行
    container:
      image: ros:humble-ros-base # 指定自定义 Docker 镜像
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1000
        fetch-tags: true

    - name: Run build script
      run: |
        bash build.sh


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: interfaces-artifacts
        path: artifacts
    
    - name: Trigger downstream CI
      run: |
        apt-get update
        apt-get install -y curl
        curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/kaylorchen/micro_ros_stm32cubemx_utils/dispatches \
            -d '{"event_type":"trigger"}'